include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: true
    use_key_in_widget_constructors: false
    sort_child_properties_last: false

analyzer:
  plugins:
    - custom_lint
