name: distress
description: "A mobile app for the Hospitallers Training Center."
publish_to: 'none'
version: 0.1.0
repository: https://github.com/kraianyn/distress

environment:
  sdk: ^3.4.3

dependencies:
  flutter:
    sdk: flutter

  collection: ^1.18.0

  firebase_core: ^3.3.0
  cloud_firestore: ^5.2.0

  flutter_hooks: ^0.20.5
  hooks_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  google_fonts: ^6.2.1

dev_dependencies:
  flutter_lints: ^4.0.0
  riverpod_lint: ^2.3.10
  custom_lint: ^0.6.4

  build_runner: ^2.4.11
  riverpod_generator: ^2.4.0

flutter:
  uses-material-design: true
