name: distress
description: "A mobile app for the Hospitallers Training Center."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.4.3

dependencies:
  flutter:
    sdk: flutter

  flutter_hooks: ^0.20.5

dev_dependencies:
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
